### ISSUE TITLE
Server doesn't boot (probably looking for client-side registries)

### ISSUE THREAD

**Issue by Desempregago** [NukeMinecart/ThaumicTweaker#1]
<details>
<summary>---- Minecraft Crash Report ----</summary>
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Ooh. Shiny.

Time: 2024-02-08 00:33:46 UTC
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumic Tweaker (thaumictweaker)
Caused by: java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.item.EnumDyeColor.func_192396_c()'
    at nukeminecart.thaumictweaker.recipes.thaumcraft.ThaumcraftArcaneRecipes.initializeArcaneRecipes(ThaumcraftArcaneRecipes.java:43)
    at nukeminecart.thaumictweaker.Registrar.registerVanillaRecipes(Registrar.java:33)
    at nukeminecart.thaumictweaker.ThaumicTweaker.postInit(ThaumicTweaker.java:36)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
    at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
    at com.google.common.eventbus.EventBus.post(EventBus.java:270)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:279)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:257)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
    at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
    at com.google.common.eventbus.EventBus.post(EventBus.java:270)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:193)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 6.1.0-17-cloud-amd64
  Java Version: 21.0.2, Eclipse Adoptium
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
  Memory: 712028304 bytes (679 MB) / 1048576000 bytes (1000 MB) up to 3145728000 bytes (3000 MB)
  JVM Flags: 2 total; -Xms1000M -Xmx3000M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.18 VintageFix 0.4.0 Powered by Cleanroom 14.23.5.0 90 mods loaded, 90 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                           | Version          | Source                                                  | Signature                                |
       |:----- |:---------------------------- |:---------------- |:------------------------------------------------------- |:---------------------------------------- |
       | LCHIJ | minecraft                    | 1.12.2           | minecraft.jar                                           | None                                     |
       | LCHIJ | mcp                          | 9.42             | minecraft.jar                                           | None                                     |
       | LCHIJ | FML                          | 8.0.99.99        | cleanroom.jar                                           | None                                     |
       | LCHIJ | forge                        | 14.23.5.0        | cleanroom.jar                                           | None                                     |
       | LCHIJ | xaerominimap_core            | 1.12.2-1.0       | minecraft.jar                                           | None                                     |
       | LCHIJ | xaeroworldmap_core           | 1.12.2-1.0       | minecraft.jar                                           | None                                     |
       | LCHIJ | mixinbooter                  | 100.0            | minecraft.jar                                           | None                                     |
       | LCHIJ | configanytime                | 1.0              | !configanytime-2.0.jar                                  | None                                     |
       | LCHIJ | redcore                      | 0.6-Dev-1        | !Red-Core-MC-1.7-1.12-0.6-Dev-1.jar                     | None                                     |
       | LCHIJ | betterfarmland               | 0.0.8 BETA       | [1.12.2] BetterFarmland-v0.0.8-BETA.jar                 | None                                     |
       | LCHIJ | baubles                      | 1.5.2            | Baubles-1.12-1.5.2.jar                                  | None                                     |
       | LCHIJ | thaumcraft                   | 6.1.BETA26       | Thaumcraft-1.12.2-6.1.BETA26.jar                        | None                                     |
       | LCHIJ | thaumicaugmentation          | 1.12.2-2.1.11    | ThaumicAugmentation-1.12.2-2.1.11.jar                   | None                                     |
       | LCHIJ | advanced_alchemy_furnace     | 0.2.2            | AdvancedAlchemyFurnace-0.2.2.jar                        | None                                     |
       | LCHIJ | appliedenergistics2          | rv6-stable-7     | ae2-uel-extended-v0.55.30-0.4.0.2-rv6-stable-7.jar      | None                                     |
       | LCHIJ | bdlib                        | 1.14.4.1         | bdlib-1.14.4.1-mc1.12.2.jar                             | None                                     |
       | LCHIJ | ae2stuff                     | v0.8-0.2         | ae2stuff-extended-1.12.2-v0.8-0.2.1.jar                 | None                                     |
       | LCHIJ | crafttweaker                 | 4.1.20           | CraftTweaker2-1.12-4.1.20.698.jar                       | None                                     |
       | LCHIJ | mtlib                        | 3.0.7            | MTLib-3.0.7.jar                                         | None                                     |
       | LCHIJ | modtweaker                   | 4.0.19           | modtweaker-4.0.20.11.jar                                | None                                     |
       | LCHIJ | jei                          | 4.25.1           | HadEnoughItems_1.12.2-4.25.1.jar                        | None                                     |
       | LCHIJ | appleskin                    | 1.0.14           | AppleSkin-mc1.12-1.0.14.jar                             | None                                     |
       | LCHIJ | aquaacrobatics               | 1.15.3           | AquaAcrobatics-1.15.3.jar                               | None                                     |
       | LCHIJ | aroma1997core                | 2.0.0.2.b167     | Aroma1997Core-1.12.2-2.0.0.2.b167.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJ | aroma1997sdimension          | 2.0.0.2.b97      | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b97.jar     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJ | quark                        | r1.6-179         | Quark-r1.6-179.jar                                      | None                                     |
       | LCHIJ | autoreglib                   | 1.3-32           | AutoRegLib-1.3-32.jar                                   | None                                     |
       | LCHIJ | bettermagnets                | 1.2              | bettermagnets-1.2.jar                                   | None                                     |
       | LCHIJ | bookshelf                    | 2.3.590          | Bookshelf-1.12.2-2.3.590.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJ | bmtr                         | 0.4              | BringMeTheRings-0.4.jar                                 | None                                     |
       | LCHIJ | buildinggadgets              | 2.8.4            | BuildingGadgets-2.8.4.jar                               | None                                     |
       | LCHIJ | loliasm                      | 5.18             | censoredasm5.18.jar                                     | None                                     |
       | LCHIJ | codechickenlib               | 3.2.3.358        | CodeChickenLib-1.12.2-3.2.3.358-universal.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJ | redstoneflux                 | 2.1.1            | RedstoneFlux-1.12-2.1.1.1-universal.jar                 | None                                     |
       | LCHIJ | cofhcore                     | 4.6.6            | CoFHCore-1.12.2-4.6.6.1-universal.jar                   | None                                     |
       | LCHIJ | cofhworld                    | 1.4.0            | CoFHWorld-1.12.2-1.4.0.1-universal.jar                  | None                                     |
       | LCHIJ | collective                   | 3.0              | collective-1.12.2-3.0.jar                               | None                                     |
       | LCHIJ | crafttweakerjei              | 2.0.3            | CraftTweaker2-1.12-4.1.20.698.jar                       | None                                     |
       | LCHIJ | cyclicmagic                  | 1.20.12          | Cyclic-1.12.2-1.20.14.jar                               | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
       | LCHIJ | elegant_networking           | 3.16             | elegant-networking-1.12-3.16.jar                        | None                                     |
       | LCHIJ | elevatorid                   | 1.4.2            | ElevatorMod-1.12.2-1.4.2.jar                            | None                                     |
       | LCHIJ | eplus                        | 5.1.0            | EnchantingPlusPlus-1.12.2-5.1.0.jar                     | None                                     |
       | LCHIJ | enchxchg                     | 1.2.14           | enchxchg-1.12.2-1.2.14.jar                              | None                                     |
       | LCHIJ | entitydistance               | 1.0.2            | entitydistance-1.0.2.jar                                | None                                     |
       | LCHIJ | exhaustedstamina             | 1.2              | exhaustedstamina-1.2.jar                                | None                                     |
       | LCHIJ | xporbclump                   | 2.0              | Fixeroo-2.0.jar                                         | None                                     |
       | LCHIJ | ftblib                       | 5.4.7.2          | FTBLib-5.4.7.2.jar                                      | None                                     |
       | LCHIJ | ftbutilities                 | 5.4.1.131        | FTBUtilities-5.4.1.131.jar                              | None                                     |
       | LCHIJ | fugue                        | 1.12.2-0.5.4     | Fugue-1.12.2-0.5.4.jar                                  | None                                     |
       | LCHIJ | hammercore                   | 12.2.47          | HammerLib-1.12.2-12.2.47.jar                            | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJ | waila                        | 1.8.26           | Hwyla-1.8.26-B41_1.12.2.jar                             | None                                     |
       | LCHIJ | jaopca                       | 1.12.2-2.2.8.106 | JAOPCA-1.12.2-2.2.8.106.jar                             | None                                     |
       | LCHIJ | oredictinit                  | 1.12.2-2.2.1.72  | JAOPCA-1.12.2-2.2.8.106.jar                             | None                                     |
       | LCHIJ | jaopcaoc                     | 1.0.11           | JAOPCAOC-1.12.2-1.0.13.jar                              | None                                     |
       | LCHIJ | logicalarmorrework           | 1.0              | logicalarmorrework-1.12.2-1.0.jar                       | None                                     |
       | LCHIJ | maleksinfinitygauntlet       | 1.0              | maleksinfinitygauntlet.jar                              | None                                     |
       | LCHIJ | mantle                       | 1.12-1.3.3.55    | Mantle-1.12-1.3.3.55.jar                                | None                                     |
       | LCHIJ | mekanism                     | 9.12.8           | Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar       | None                                     |
       | LCHIJ | mekanismgenerators           | 9.12.8           | Mekanism-Community-Edition-1.12.2-9.12.8-Generators.jar | None                                     |
       | LCHIJ | mekanismfluxified            | 1.0.0            | mekanismfluxified-1.12.2-1.0.0.jar                      | None                                     |
       | LCHIJ | modification-of-critical-hit | 1.0              | modification-of-critical-hit-1.12.2-forge-1.0.jar       | None                                     |
       | LCHIJ | multithreadednoise           | 0.0.2            | MultithreadedNoise-1.12.2-0.0.2.jar                     | None                                     |
       | LCHIJ | naturescompass               | 1.8.5            | NaturesCompass-1.12.2-1.8.5.jar                         | None                                     |
       | LCHIJ | netherportalfix              | 5.3.17           | NetherPortalFix_1.12.1-5.3.17.jar                       | None                                     |
       | LCHIJ | noarcher                     | 1.0.0            | noarcher-1.0.0.jar                                      | None                                     |
       | LCHIJ | nodami                       | 1.2.4            | nodami-1.12.2-1.2.5.jar                                 | None                                     |
       | LCHIJ | oreexcavation                | 1.4.150          | OreExcavation-1.4.150.jar                               | None                                     |
       | LCHIJ | oeintegration                | 2.3.4            | oeintegration-2.3.4.jar                                 | None                                     |
       | LCHIJ | reachfix                     | 1.0.9            | ReachFix-1.12.2-1.0.9.jar                               | None                                     |
       | LCHIJ | bettercombatmod              | 2.1.0            | RLCombat-1.12.2-2.1.0.jar                               | None                                     |
       | LCHIJ | sledgehammer                 | 1.12.2-2.0.25    | Sledgehammer-1.12.2-2.0.25.jar                          | None                                     |
       | LCHIJ | thaumcraftnoresearch         | 1.0              | ThaumcraftNoResearch-1.0.jar                            | None                                     |
       | LCHIJ | thaumadditions               | 12.7.8           | ThaumicAdditions-1.12.2-12.7.8.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJ | thaumic_mercy                | 0.2              | ThaumicMercy-0.2.jar                                    | None                                     |
       | LCHIJ | thaumicperiphery             | 0.3.1            | thaumicperiphery-0.3.1.jar                              | None                                     |
       | LCHIJ | thaumicterminal              | 1.0.12           | ThaumicTerminal-1.0.12.jar                              | None                                     |
       | LCHIE | thaumictweaker               | 1.1.2            | ThaumicTweaker-1.1.2.jar                                | None                                     |
       | LCHI  | torchmaster                  | 1.8.5.0          | torchmaster_1.12.2-1.8.5.0.jar                          | None                                     |
       | LCHI  | universaltweaks              | 1.9.0            | UniversalTweaks-1.12.2-1.9.0.jar                        | None                                     |
       | LCHI  | vanillasatchels              | 1.0.2            | VanillaSatchels-1.12.2-1.0.2.4-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHI  | villagespawnpoint            | 1.8              | villagespawnpoint_1.12.2-1.8.jar                        | None                                     |
       | LCHI  | vintagefix                   | 0.4.0            | vintagefix-0.4.0.jar                                    | None                                     |
       | LCHI  | vintagium                    | 0.1              | vintagium-mc1.12.2-0.1.jar                              | None                                     |
       | LCHI  | wanionlib                    | 1.12.2-2.91      | WanionLib-1.12.2-2.91.jar                               | None                                     |
       | LCHI  | wawla                        | 2.6.275          | Wawla-1.12.2-2.6.275.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | xaerominimap                 | 23.9.7           | Xaeros_Minimap_23.9.7_Forge_1.12.jar                    | None                                     |
       | LCHI  | xaeroworldmap                | 1.37.8           | XaerosWorldMap_1.37.8_Forge_1.12.jar                    | None                                     |
       | LCHI  | phosphor-lighting            | 1.12.2-0.2.9.3   | phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar                    | None                                     |
       | LCHI  | unidict                      | 1.12.2-3.0.10    | UniDict-1.12.2-3.0.10.jar                               | None                                     |
       | LCHI  | wrapup                       | 1.12-1.1.3       | WrapUp-1.12-1.1.3.jar                                   | None                                     |
  Loaded coremods (and transformers): Aqua Acrobatics Transformer (AquaAcrobatics-1.15.3.jar)
                                        
                                      HCASM (HammerLib-1.12.2-12.2.47.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VintageFix (vintagefix-0.4.0.jar)
                                        org.embeddedt.vintagefix.transformer.ASMModParserTransformer
                                      UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
                                        wanion.unidict.core.UniDictCoreModTransformer
                                      PhosphorFMLPlugin (phosphor-1.12.2-0.2.9.3-SNAPSHOT.jar)
                                        
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.37.8_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.EntityPlayerMPTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.SaveFormatTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                        xaero.map.core.transformer.MinecraftServerTransformer
                                        xaero.map.core.transformer.MinecraftTransformer
                                      Red Core (!Red-Core-MC-1.7-1.12-0.6-Dev-1.jar)
                                        
                                      ReachFixPlugin (ReachFix-1.12.2-1.0.9.jar)
                                        meldexun.reachfix.asm.ReachFixClassTransformer
                                      AE2ELCore (ae2-uel-extended-v0.55.30-0.4.0.2-rv6-stable-7.jar)
                                        appeng.core.transformer.AE2ELTransformer
                                      BringMeTheRings plugin (BringMeTheRings-0.4.jar)
                                        zabi.minecraft.bmtr.core.BaublesTransformer
                                      LoliASM (censoredasm5.18.jar)
                                        
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
                                        
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.9.0.jar)
                                        
                                      LARCoremod (logicalarmorrework-1.12.2-1.0.jar)
                                        
                                      MixinBooter (cleanroom.jar)
                                        
                                      XaeroMinimapPlugin (Xaeros_Minimap_23.9.7_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerMPTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.SaveFormatTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.MinecraftServerTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.11.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      Fixeroo (Fixeroo-2.0.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Sodium (vintagium-mc1.12.2-0.1.jar)
                                        
                                      MekanismCoremod (Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      MekanismTweaks (mekanismtweaks-1.1.jar)
                                        
                                      FugueLoadingPlugin (Fugue-1.12.2-0.5.4.jar)
                                        com.cleanroommc.transformer.CommonRegistrar$Transformer
                                      ExampleModLoadingPlugin (maleksinfinitygauntlet.jar)
                                        
                                      ConfigAnytimePlugin (!configanytime-2.0.jar)
                                        
                                      TARCore (ThaumicAdditions-1.12.2-12.7.8.jar)
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2847
  HammerCore Debug Information: Dependent Mods:
                                -Thaumic Additions: Reconstructed (thaumadditions) @ 12.7.8
  List of loaded APIs: * appliedenergistics2|API (rv6) from ae2-uel-extended-v0.55.30-0.4.0.2-rv6-stable-7.jar
                       * Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
                       * BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.14.jar
                       * cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.6.1-universal.jar
                       * ctm-api (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * ctm-api-events (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * ctm-api-models (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * ctm-api-textures (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * ctm-api-utils (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
                       * JustEnoughItemsAPI (4.13.0) from HadEnoughItems_1.12.2-4.25.1.jar
                       * MekanismAPI|core (9.8.1) from Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar
                       * MekanismAPI|energy (9.8.1) from Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar
                       * MekanismAPI|gas (9.8.1) from Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar
                       * MekanismAPI|infuse (9.8.1) from Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar
                       * MekanismAPI|laser (9.8.1) from Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar
                       * MekanismAPI|transmitter (9.8.1) from Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar
                       * MekanismAPI|util (9.0.0) from Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar
                       * MouseTweaks|API (1.0) from mousetweaks-1.12.2-3.1.4.jar
                       * QuarkAPI (4) from Quark-r1.6-179.jar
                       * redstonefluxapi (2.1.1) from RedstoneFlux-1.12-2.1.1.1-universal.jar
                       * Thaumcraft|API (6.0.2) from Thaumcraft-1.12.2-6.1.BETA26.jar
                       * thaumicaugmentationapi (2.1.11) from ThaumicAugmentation-1.12.2-2.1.11.jar
                       * WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
  AE2 Integration: IC2:OFF, GTCE:OFF, RC:OFF, MFR:OFF, Waila:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: java.lang.IllegalArgumentException: URI scheme is not "file"
                      at java.base/java.io.File.<init>(Unknown Source)
                      at zone.rong.loliasm.common.crashes.ModIdentifier.identifyFromClass(ModIdentifier.java:64)
                      at zone.rong.loliasm.common.crashes.ModIdentifier.identifyFromStacktrace(ModIdentifier.java:34)
                      at net.minecraft.crash.CrashReport.md1aa783$lambda$afterPopulateEnvironment$0$0(CrashReport.java:550)
                      at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
                      at net.minecraft.crash.CrashReport.handler$zhb000$afterPopulateEnvironment(CrashReport.java:548)
                      at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:128)
                      at net.minecraft.crash.CrashReport.<init>(CrashReport.java:48)
                      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
                      at java.base/java.lang.Thread.run(Unknown Source)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

</details>

**Comment by NukeMinecart** [comment]
The newest version fixes this
